# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
- 导入 numpy 使用 np

(**hint**: import … as …)

In [51]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
- 输出 numpy 版本以及配置

(**hint**: np.\_\_version\_\_, np.show\_config)

In [52]:
np.__version__

'1.17.3'

In [53]:
np.show_config()


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
- 构建一个0长度为10的数组

(**hint**: np.zeros)

In [54]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
- 如何找到数组的内存大小(数组大小 x 每个元素的大小)

(**hint**: size, itemsize)

In [55]:
a =  np.zeros(10)
a.size * a.itemsize


80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
- 如何查看文档关于 numpy.add函数

(**hint**: np.info)

In [56]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
- 创建一个长度为 10 第五个位置为 1 ,为0

(**hint**: array\[4\])

In [57]:
d = np.zeros(10)
d[4]=1
d


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
- 创建数组10-49

(**hint**: np.arange)

In [58]:
np.arange(10,49)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
- 反转list

(**hint**: array\[::-1\])

In [59]:
np.arange(10)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
- 创建 3x3 矩阵 数值为0-8

(**hint**: reshape)

In [60]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
- 从数组中找出不为零的元素

(**hint**: np.nonzero)

In [61]:
d = np.array([1,2,0,0,4,0])
np.nonzero(d)


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
- 创建 3x3 对角线为1 矩阵

(**hint**: np.eye)

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
- 创建 3x3x3 随机矩阵

(**hint**: np.random.random)

In [64]:
np.random.random((3,3,3))


array([[[0.86702394, 0.43191325, 0.98313851],
        [0.10785258, 0.19969846, 0.01005837],
        [0.52711226, 0.78486635, 0.31048263]],

       [[0.29891299, 0.02891522, 0.35628337],
        [0.66080826, 0.51229827, 0.18540945],
        [0.30855515, 0.57825096, 0.12580469]],

       [[0.68541518, 0.09636427, 0.65156977],
        [0.74332472, 0.0211267 , 0.13622469],
        [0.80004217, 0.11643504, 0.42551839]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
- 创建10x10随机数矩阵 求出最大最小值

(**hint**: min, max)

In [65]:
d = np.random.random((10,10))
d

array([[0.61972684, 0.29863152, 0.86782636, 0.42321577, 0.88194742,
        0.45196247, 0.48526399, 0.61683043, 0.51680479, 0.86202582],
       [0.99966924, 0.39483495, 0.85402851, 0.30829144, 0.75917077,
        0.65965184, 0.55541862, 0.56959945, 0.48841303, 0.39087506],
       [0.62937775, 0.38354064, 0.3181813 , 0.45640411, 0.32948382,
        0.30079115, 0.87665779, 0.53220005, 0.10917168, 0.55211747],
       [0.42711313, 0.07335942, 0.32304323, 0.19060152, 0.84251665,
        0.50105316, 0.15600167, 0.4031435 , 0.11194752, 0.39931194],
       [0.08438677, 0.61740147, 0.86830153, 0.35903547, 0.33002776,
        0.47877627, 0.89670115, 0.0710599 , 0.90352208, 0.95646744],
       [0.89052784, 0.7909664 , 0.71884146, 0.93897776, 0.91275057,
        0.18197991, 0.13064629, 0.7657171 , 0.31036947, 0.67277123],
       [0.21485019, 0.96237125, 0.40665115, 0.76917771, 0.97877462,
        0.90935979, 0.99412083, 0.76097134, 0.67583385, 0.85227405],
       [0.59741231, 0.16941682, 0.1895155

In [66]:
np.max(d)

0.9996692430582399

In [67]:
d.max()

0.9996692430582399

In [68]:
np.min(d)

0.019083556877752872

In [69]:
d.min()


0.019083556877752872

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
- 随机数组长度为30求平均值

(**hint**: mean)

In [70]:
d = np.random.random(30)
d.mean()


0.5889326531482257

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
- 创建矩阵中间为 0 ,外圈为1

(**hint**: array\[1:-1, 1:-1\])

In [71]:
d = np.ones((3,4))
d[1:-1,1:-1]=0
d



array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
- 在原有数组上向外追加一圈0

(**hint**: np.pad)

In [72]:
Z = np.ones((2,2))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
- 回答下面计算结果

(**hint**: NaN = not a number, inf = infinity)

```python
import numpy as np
0 * np.nan 
np.nan == np.nan 
np.inf > np.nan 
np.nan - np.nan 
np.nan in set([np.nan]) 
0.3 == 3 * 0.1 
```

In [73]:
# 回答 np.nan , 原因: np.nan 乘任何数都是np.nan
0 * np.nan

nan

In [74]:
# 回答 True 回答错误!!! 笔者不知道如何解答 , 答案为False,如果需要判断nan使用`np.isnan`方法
np.nan == np.nan

False

In [75]:
np.isnan(np.nan)

True

In [76]:
# 回答 True 回答错误!!! 主观上笔者认为无穷大>不存在. T_T
np.inf > np.nan 

False

- 参与计算时使用 np.nan_to_num()

In [77]:
np.nan_to_num(np.inf) > np.nan_to_num(np.nan)

True

In [78]:
# 回答 np.nan
np.nan - np.nan 

nan

In [79]:
# 回答 True
np.nan in set([np.nan]) 

True

In [80]:
# 回答 False
0.3 == 3 * 0.1 



False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
- 创建5x5矩阵对角线[1,2,3,4]

(**hint**: np.diag)

In [81]:
d = np.diag(1+np.arange(4))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
- 创建8x8矩阵形状和国际象棋类似0101010排列

(**hint**: array\[::2\])

In [82]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
- 一个数组结构shape=(6,7,8),求第100个元素的坐标(x,y,z)

(**hint**: np.unravel_index)

In [83]:
np.unravel_index(100,(6,7,8))


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
- 用`np.tile`创建棋盘 

(**hint**: np.tile)

In [84]:
# 设定左上角[[0,1],[1,0]],那么横轴还需要4,纵轴还需要4,(4,4)
np.tile(np.array([[0,1],[1,0]]),(4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
- 5*5 随机矩阵归一化处理

(**hint**: (x - mean) / std)

In [85]:
d = np.random.random((5,5))
d = ( d-np.mean(d) ) / (np.std(d))
d

array([[-0.15185698, -1.30446595,  0.3424399 , -0.4538171 , -0.01117507],
       [-1.27617598,  0.29049351, -1.20140968, -0.98010261, -0.40923365],
       [-0.16554677,  0.93284831,  0.90840323, -1.32418952,  1.20935014],
       [-1.6544167 ,  0.46669631, -0.30021511,  1.43144603,  0.74926258],
       [ 1.43173197,  1.40904524, -1.60530645,  0.64224729,  1.02394706]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [86]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


color

e:\pycharm_project\python_doc\venv2\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
- 两个矩阵相乘

(**hint**: np.dot | @)

In [87]:
a = np.ones((5,3))
b = np.random.random((3,2))
np.dot(a,b)

array([[1.00635972, 1.50039345],
       [1.00635972, 1.50039345],
       [1.00635972, 1.50039345],
       [1.00635972, 1.50039345],
       [1.00635972, 1.50039345]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
- 给定一个矩阵,在3-8范围内取反

(**hint**: >, <=)

In [88]:
a = np.arange(10)
a[(3<a)&(a<8)] *=-1
a



array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆) 

(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [89]:
# [0,1,2,3,4] + -1
print(sum(range(5),-1))
from numpy import *
# -1 是参数维度( axis ) 一维数据的-1维度就是自己([0, 1, 2, 3, 4])
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z  合法
2 << Z >> 2 不合法
Z <- Z 合法
1j*Z 合法
Z/1/1 合法
Z<Z>Z 不合法
```




#### 28. What are the result of the following expressions?

```python
import numpy as np
np.array(0) / np.array(0) # np.nan
np.array(0) // np.array(0) # 0
np.array([np.nan]).astype(int).astype(float)
```

In [90]:
np.array(0) / np.array(0) # np.nan

e:\pycharm_project\python_doc\venv2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [91]:
np.array(0) // np.array(0) # 0

e:\pycharm_project\python_doc\venv2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [92]:
np.array([np.nan]).astype(int).astype(float)



array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
- 四舍五入取整

(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [93]:
Z = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([-5., -3., -1.,  6., -6., -9.,  6.,  6., -1., 10.])

#### 30. How to find common values between two arrays? (★☆☆) 
- 两个数组共同部分

(**hint**: np.intersect1d)

In [94]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
np.intersect1d(a,b)


array([0, 2, 4, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
- 如何忽略所有警告

(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)
```

np.sqrt(-1) = np.nan
np.emath.sqrt(-1) = 1j
np.nan == 1j ==> False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
- 输出今天、昨天、明天 

(**hint**: np.datetime64, np.timedelta64)

In [95]:
today = np.datetime64("today","D")
yesterday = today - np.timedelta64(1,"D")
tomorrow  = today + np.timedelta64(1,"D")
print(today)
print(yesterday)
print(tomorrow)

2019-10-31
2019-10-30
2019-11-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
- 获取2016年7月的所有日期

(**hint**: np.arange(dtype=datetime64\['D'\]))

In [96]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
- 题目看不懂,直接用函数

(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [97]:
a = np.arange(10)
b = np.arange(10)
np.add(a,b,out=a)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
a = np.arange(10)
np.negative(a,out=a)

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [99]:
a = np.arange(10)
b = np.arange(10)
np.multiply(a,b,out=a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
a = np.arange(10)
# 当前版本不支持
np.divide(a,2,out=a)


TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
- 提取整数部分

(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
- 创建5x5矩阵每行0-4

(**hint**: np.arange)

In [ ]:
np.broadcast_to(np.arange(5),shape=(5,5))

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
- 通过生成器函数来返回一个数组
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
- 随机创建10个数字,范围0-1不包括0,1

(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:] # 第一个是0去掉
Z

#### 40. Create a random vector of size 10 and sort it (★★☆) 
- 随机10个数排序

(**hint**: sort)

In [ ]:
Z = np.random.random(10)
Z.sort()
Z

#### 41. How to sum a small array faster than np.sum? (★★☆) 
- 小型数组如何求和

(**hint**: np.add.reduce)

In [ ]:
np.add.reduce(np.arange(10))


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
- 两个数组比较是否相等
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.arange(10)
B = np.arange(10)
print(np.array_equal(A,B))
print(np.allclose(A,B))

#### 43. Make an array immutable (read-only) (★★☆) 
- 创建只读数组

(**hint**: flags.writeable)

In [ ]:
A = np.arange(10)
A.flags.writeable = False
A[1]= 100



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
- 创建随机数组长度10,最大值替换0

(**hint**: argmax)

In [101]:
Z = np.random.random(10)
Z[Z.argmax()] = 0


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)