# 数组操作

## 数组创建
- 通过`np.array` + `ndarry.reshape`

In [55]:
import numpy as np
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [56]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [61]:
np.array([[1,2,3]]).reshape((1,3,1))

array([[[1],
        [2],
        [3]]])

- 通过`np.arange` + `ndarry.reshape`

In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- `np.zeros` 创建元素为 0 的数组

In [63]:
np.zeros(2)

array([0., 0.])

In [66]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- `np.ones` 创建元素为 1 的数组

In [67]:
np.ones(2)

array([1., 1.])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- `np.identity` 创建对角线为 1 的数组,其他为 0 的数组 

In [69]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- `np.diag` 创建对角线数字,其他为 0 的数组 

In [70]:
np.diag([1,2,3])


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## 拷贝数组
- `np.copy`

In [2]:
import numpy as np
a = np.arange(10)

b = np.copy(a)
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 维度修改
- `np.atleast_1d` 返回至少1维数据
- `np.atleast_2d` 返回至少2维数据
- `np.atleast_3d` 返回至少3维数据
- 广播
    - `np.broadcast_to` 
    - `np.broadcast`
- `np.expand_dims`

In [10]:
a = np.array([
    [[1,2]],
    [[1,2]]
])

array([[[1, 2]],

       [[1, 2]]])

In [12]:
a

array([[[1, 2]],

       [[1, 2]]])

In [11]:
np.atleast_1d(a)

array([[[1, 2]],

       [[1, 2]]])

In [15]:
np.atleast_1d(1)

array([1])

In [16]:
np.atleast_2d(1)

array([[1]])

In [17]:
np.atleast_3d(1)

array([[[1]]])

In [4]:
x = np.array([1, 2, 3])
np.broadcast_to(array=x , shape=(3,3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
np.expand_dims(x,axis=1)

array([[1],
       [2],
       [3]])

## 拆分数组

- `np.split` 直接拆分,拆分数需要能够整除原始数组的长度

In [54]:
a = np.arange(10)
b = np.split(a,2)
b


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

- `np.array_split` 直接拆分,区别于`np.split`不需要整除关系

In [53]:
a = np.arange(10)
np.array_split(a,3)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

- `np.dsplit` 按照深度拆分


In [51]:
x = np.arange(16).reshape(2, 2, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
np.dsplit(x, 2)


[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

- `np.hsplit` 水平拆分


In [48]:
x = np.arange(16.0).reshape(4, 4)
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

- `np.vsplit` 垂直拆分



In [23]:
x = np.arange(16.0).reshape(4, 4)
np.vsplit(x, 2)


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

## 增加或删除
- `np.delete`

In [28]:
x = np.arange(10)
np.delete(x,[1,2,3])

array([0, 4, 5, 6, 7, 8, 9])

In [35]:
x = np.array([
    [1,2,3],
    [4,5,6]
])
np.delete(x,np.s_[1:2])

array([1, 3, 4, 5, 6])

- `np.insert`

In [40]:
x = np.array([
    [1,2,3],
    [4,5,6]
])

np.insert(x ,1,[1,2,3])

array([1, 1, 2, 3, 2, 3, 4, 5, 6])

- `np.trim_zeros`删除两头的0

In [46]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

- `np.unique`唯一值

In [47]:
x = np.array([
    [1,2,3],
    [4,5,6]
])
np.unique(x)

array([1, 2, 3, 4, 5, 6])