# numpy copy


## 浅拷贝
- 不同对象可以共享同一个数据,采用`view`实现,**任意对象修改后原始数据也会被修改**

In [15]:
import numpy as np

a = np.arange(10)

b= a 

b is a

True

In [21]:
c = a.view()
c is a

False

In [23]:
c[0]=111
c

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
a

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## 深拷贝
- 使用`copy`进行完整的数据副本

In [25]:
import numpy as np
a = np.arange(10)
b = a.copy()
b is a


False

In [26]:
b[1]=112313
b

array([     0, 112313,      2,      3,      4,      5,      6,      7,
            8,      9])

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])