# 线性代数
- 主要库np.linalg

In [58]:
import numpy as np


- `np.dot`两个数组点积

In [6]:
np.dot(1, 2)

2

- `np.vdot`两个向量点积

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])

np.vdot(a,b)

30

- `np.inner`两个数组的内积

In [7]:
np.inner(a,b)

array([[ 5, 11],
       [11, 25]])

- `np.outer`计算两个向量的外积

In [8]:
np.outer(a,b)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

- `np.matmul`两个数组的矩阵乘积

In [9]:
np.matmul(a,b)

array([[ 7, 10],
       [15, 22]])

- `np.kron`Kronecker乘积

In [10]:
np.kron(a,b)

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 3,  6,  4,  8],
       [ 9, 12, 12, 16]])

## 矩阵分解

- `np.linalg.cholesky`Cholesky 分解

In [17]:
A=  np.array([
    [1,3],
    [1,3]
])
L = np.linalg.cholesky(A)
L

array([[1.        , 0.        ],
       [1.        , 1.41421356]])

- `np.linalg.qr` QR 分解

In [21]:
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = np.linalg.qr(A)
q

array([[-2.44948974, -1.63299316],
       [ 0.        ,  1.15470054]])

In [22]:
r

array([[-2.44948974, -1.63299316],
       [ 0.        ,  1.15470054]])

- `np.linalg.svd`奇异分解

In [59]:
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
u, s, vh = np.linalg.svd(A)

In [28]:
u

array([[-0.20374866,  0.84171639, -0.33061251,  0.37509381],
       [-0.46470513,  0.18452409, -0.19985025, -0.84265051],
       [-0.46470513,  0.18452409,  0.86107527,  0.09246288],
       [-0.72566161, -0.47266821, -0.33061251,  0.37509381]])

In [29]:
s

array([3.02044792, 0.93642638])

In [30]:
vh


array([[-0.78820544, -0.61541221],
       [-0.61541221,  0.78820544]])

## 其他
- `np.linalg.solve`求解线性矩阵方程或线性标量方程组 

In [41]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [42]:
np.allclose(np.tensordot(a, x, axes=1), b)

True

- `np.linalg.tensorsolve`对x求解张量方程a x = b。

In [43]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.tensorsolve(a, b)
x

array([2., 3.])

In [44]:
np.allclose(np.tensordot(a, x, axes=1), b)

True

- `np.linalg.lstsq`返回线性矩阵方程的最小二乘解

In [49]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
(m,c)

(0.9999999999999999, -0.9499999999999997)

- `np.linalg.inv`求逆矩阵

In [50]:
a = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

- `np.linalg.pinv`伪逆矩阵

In [51]:
a = np.random.randn(9, 6)
B = np.linalg.pinv(a)
B

array([[ 0.10260931, -0.10522441, -0.25414171,  0.05881647,  0.06097556,
        -0.00196579,  0.0833756 , -0.09219846,  0.11423058],
       [ 0.33274769, -0.69678795, -0.03102913, -0.32111589,  0.11040638,
        -0.52829896,  0.11165537, -0.20432787,  0.44413509],
       [-0.19509093,  0.33703715, -0.01012723,  0.35507018,  0.06873478,
         0.33434522, -0.25834098,  0.10371736, -0.19451881],
       [ 0.25839757, -0.20193452,  0.02801389, -0.43954135,  0.17414198,
        -0.14981802,  0.04243574, -0.10099703,  0.28628872],
       [-0.11062591,  0.35905905, -0.01026444,  0.05262695,  0.16050458,
         0.08394923, -0.09299729,  0.14463897, -0.33686455],
       [-0.15089442,  0.48359936, -0.18790734, -0.13368641, -0.05485233,
        -0.00468638,  0.00693476, -0.10534536, -0.07393006]])

In [52]:
np.allclose(a, np.dot(a, np.dot(B, a)))

True

In [53]:
np.allclose(B, np.dot(B, np.dot(a, B)))

True

- `np.linalg.tensorinv`N维逆

In [57]:
a=  np.eye(4*6)
a.shape = (4, 6, 8, 3)
ainv = np.linalg.tensorinv(a, )
ainv

array([[[[1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

  