# NumPy 数额学函数

## sin 正弦

In [284]:
import numpy as np 
x = np.arange(11)[1:]
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

## cos 余弦

In [285]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

## tan 正切
np.tan(x)

In [286]:
np.tan(x)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

## arcsin 反正弦

In [287]:
np.arcsin(x)

e:\pycharm_project\python_doc\venv2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan])

## arccos 反余弦

In [288]:
np.arccos(x)

e:\pycharm_project\python_doc\venv2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


array([ 0., nan, nan, nan, nan, nan, nan, nan, nan, nan])

## arctan 反正切

In [289]:
np.arctan(x)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077,
       1.40564765, 1.42889927, 1.44644133, 1.46013911, 1.47112767])

## sinh 双曲正弦

In [290]:
np.sinh(x)

array([1.17520119e+00, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
       7.42032106e+01, 2.01713157e+02, 5.48316123e+02, 1.49047883e+03,
       4.05154190e+03, 1.10132329e+04])

## cosh 双曲余弦

In [291]:
np.cosh(x)

array([1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
       4.05154203e+03, 1.10132329e+04])

## tanh 双曲正切

In [292]:
np.tanh(x)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ,
       0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ])

## arcsinh 反双曲正弦

In [293]:
np.arcsinh(x)

array([0.88137359, 1.44363548, 1.81844646, 2.09471255, 2.31243834,
       2.49177985, 2.64412076, 2.77647228, 2.89344399, 2.99822295])

## arccosh 反双曲余弦

In [294]:
np.arccosh(x)

array([0.        , 1.3169579 , 1.76274717, 2.06343707, 2.29243167,
       2.47788873, 2.63391579, 2.76865938, 2.88727095, 2.99322285])

## arctanh 反双曲正切

In [295]:
np.arctanh([0,0.5])

array([0.        , 0.54930614])

## hypot 斜边长

In [348]:
np.hypot(3,4)

5.0

## arctan2

In [351]:
np.arctan2(x,2)

array([26.56505118, 45.        , 56.30993247])

## degrees 度

In [353]:
np.degrees(x)

array([ 57.29577951, 114.59155903, 171.88733854])

## radians 弧度

In [352]:
np.radians(x)

array([0.01745329, 0.03490659, 0.05235988])

## deg2rad 度转弧度

In [300]:
np.deg2rad(x)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646,
       0.10471976, 0.12217305, 0.13962634, 0.15707963, 0.17453293])

## rad2deg 弧度转度

In [301]:
np.rad2deg(x)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757, 343.77467708, 401.07045659, 458.3662361 ,
       515.66201562, 572.95779513])

## floor 向下取整 

In [302]:
a = np.random.random(10)*10
np.floor(a)

array([0., 6., 5., 6., 1., 4., 8., 1., 7., 2.])

## around 四舍五入

In [303]:
np.around(a)

array([0., 6., 5., 7., 1., 5., 9., 2., 7., 3.])

## round 四舍五入

In [304]:
np.round(a)

array([0., 6., 5., 7., 1., 5., 9., 2., 7., 3.])

## rint 距离0远的方向取整

In [355]:
np.rint(1.2)

1.0

In [359]:
np.rint(-1.2)

-1.0

## fix 切断取整

In [354]:
np.fix(1.2)

1.0

## ceil 全部进位

In [ ]:
np.ceil(1.1)

In [362]:
np.ceil(-1.1)

-1.0

## trunc 全部舍去

In [363]:
np.trunc(1.2)

1.0

In [364]:
np.trunc(-1.2)

-1.0

## prod 相同维度乘积

In [309]:
np.prod(a)

18396.798070937864

## sum 求和

In [310]:
np.sum(a)

44.45819594644647

## nanprod 相同维度乘积(非数字当作nan)

In [311]:
np.nanprod(a)

18396.798070937864

## nansum 求和(非数字当作nan)

In [312]:
np.nanstd(a) 

2.7633115541437094

## cumprod 累计乘积

In [313]:
np.cumprod(a)

array([5.92244615e-02, 3.77865154e-01, 2.01854434e+00, 1.31463792e+01,
       1.36167954e+01, 6.39589101e+01, 5.62587952e+02, 8.67897738e+02,
       6.17235787e+03, 1.83967981e+04])

## cumsum 累计求和

In [314]:
np.cumsum(a)

array([ 0.05922446,  6.43944548, 11.78141553, 18.29421733, 19.33000027,
       24.02706067, 32.82314476, 34.36583286, 41.4776821 , 44.45819595])

## nancumprod

In [315]:
np.nancumprod(a)

array([5.92244615e-02, 3.77865154e-01, 2.01854434e+00, 1.31463792e+01,
       1.36167954e+01, 6.39589101e+01, 5.62587952e+02, 8.67897738e+02,
       6.17235787e+03, 1.83967981e+04])

## nancumsum

In [316]:
np.nancumsum(a)

array([ 0.05922446,  6.43944548, 11.78141553, 18.29421733, 19.33000027,
       24.02706067, 32.82314476, 34.36583286, 41.4776821 , 44.45819595])

## gradient 倾斜度计算

In [317]:
np.gradient(a)

array([ 6.32099655,  2.6413728 ,  0.06629039, -2.15309355, -0.9078707 ,
        3.88015058, -1.57718615, -0.84211743,  0.71891287, -4.1313354 ])

## cross 向量积 

In [318]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

## trapz 梯形数值积分

In [319]:
np.trapz(a)

42.93832679419702

## exp 以e为底数的指数函数

In [320]:
np.exp(a)

array([1.06101337e+00, 5.90058105e+02, 2.08923896e+02, 6.73711379e+02,
       2.81731117e+00, 1.09624446e+02, 6.60831575e+03, 4.67714601e+00,
       1.22641339e+03, 1.96979357e+01])

## expm1 exp(x) - 1 

In [321]:
np.expm1(a)

array([6.10133707e-02, 5.89058105e+02, 2.07923896e+02, 6.72711379e+02,
       1.81731117e+00, 1.08624446e+02, 6.60731575e+03, 3.67714601e+00,
       1.22541339e+03, 1.86979357e+01])

## exp2  2 为底的指数

In [322]:
np.exp2(a)

array([  1.04190552,  83.29863884,  40.55955874,  91.31638221,
         2.05022599,  25.93916967, 444.5137074 ,   2.9133683 ,
       138.31839682,   7.89267226])

## log 对数

In [323]:
np.log(a)

array([-2.82642062,  1.85320274,  1.67559451,  1.87376975,  0.03515761,
        1.54693686,  2.17430663,  0.43352641,  1.9617623 ,  1.09209572])

## log10 以10为底的对数

In [324]:
np.log10(a)

array([-1.22749888,  0.80483572,  0.72770145,  0.81376786,  0.01526876,
        0.67182614,  0.94428937,  0.18827813,  0.85198254,  0.47429114])

## log2 以2为底的对数

In [325]:
np.log2(a)

array([-4.07766301,  2.6736064 ,  2.41737189,  2.70327832,  0.05072171,
        2.23175814,  3.1368614 ,  0.62544641,  2.83022474,  1.57556107])

## add 加法

In [326]:
np.add(a,a)

array([ 0.11844892, 12.76044203, 10.6839401 , 13.0256036 ,  2.07156589,
        9.39412079, 17.5921682 ,  3.08537619, 14.22369848,  5.96102769])

## reciprocal 倒数

In [327]:
np.reciprocal(a)

array([16.88491501,  0.15673438,  0.18719686,  0.15354375,  0.96545324,
        0.21289911,  0.11368695,  0.64821917,  0.1406104 ,  0.33551262])

## positive 绝对值

In [328]:
np.positive(a)

array([0.05922446, 6.38022102, 5.34197005, 6.5128018 , 1.03578294,
       4.69706039, 8.7960841 , 1.5426881 , 7.11184924, 2.98051384])

## negative 相反数

In [329]:
np.negative(a)

array([-0.05922446, -6.38022102, -5.34197005, -6.5128018 , -1.03578294,
       -4.69706039, -8.7960841 , -1.5426881 , -7.11184924, -2.98051384])

## multiply 乘法

In [330]:
np.multiply(a,a)

array([3.50753685e-03, 4.07072202e+01, 2.85366440e+01, 4.24165873e+01,
       1.07284631e+00, 2.20623763e+01, 7.73710955e+01, 2.37988656e+00,
       5.05783996e+01, 8.88346277e+00])

## divide 除法

In [331]:
np.divide(a,10)

array([0.00592245, 0.6380221 , 0.53419701, 0.65128018, 0.10357829,
       0.46970604, 0.87960841, 0.15426881, 0.71118492, 0.29805138])

## power x**n

In [332]:
np.power(a,2)

array([3.50753685e-03, 4.07072202e+01, 2.85366440e+01, 4.24165873e+01,
       1.07284631e+00, 2.20623763e+01, 7.73710955e+01, 2.37988656e+00,
       5.05783996e+01, 8.88346277e+00])

## subtract 减法

In [333]:
np.subtract(a,a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## floor_divide 除法

In [334]:
np.floor_divide(a,2)

array([0., 3., 2., 3., 0., 2., 4., 0., 3., 1.])

## mod 取模

In [335]:
np.mod(a,a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## fmod 取模

In [336]:
np.fmod(a,a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## modf 取模

In [337]:
np.modf(a,a)

(array([0.05922446, 0.38022102, 0.34197005, 0.5128018 , 0.03578294,
        0.69706039, 0.7960841 , 0.5426881 , 0.11184924, 0.98051384]),
 array([0., 6., 5., 6., 1., 4., 8., 1., 7., 2.]))

## convolve

In [338]:
np.convolve(a,a)

array([0.00350754, 0.04503677, 0.18507401, 0.32078922, 0.51113801,
       0.46050262, 0.9118084 , 1.1831033 , 1.68659317, 1.43871429,
       1.92157065, 1.93400107, 2.40394576, 1.09015343, 1.83954791,
       1.68254146, 1.07673664, 0.21933946, 0.9614074 ])

## clip

In [339]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

## sqrt 开方

In [340]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## square 平方 

In [341]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

## absolute

In [342]:
np.absolute(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## fabs

In [343]:
np.fabs(a)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## sign

In [344]:
np.sign(a)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## maximum 两个矩阵(数)求最大

In [345]:
np.maximum(a,a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## minimum 两个矩阵(数)求最小

In [346]:
np.minimum(a,a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## nan_to_num nan,inf转换数字

In [365]:
np.nan_to_num(np.array([np.nan,np.inf,1]))

array([0.00000000e+000, 1.79769313e+308, 1.00000000e+000])