# 矩阵运算

### 矩阵加法 Plus
 矩阵加法: 参与运算的矩阵必须是大小一样的(n,m都一样)
 
$$
\left[
 \begin{matrix}
   1 & 2 \\
   3 & 4  
  \end{matrix} 
\right] 

+ 

\left[
 \begin{matrix}
   1 & 2 \\
   3 & 4  
  \end{matrix} 
\right] 

= 
\left[
 \begin{matrix}
   2 & 4 \\
   6 & 8  
  \end{matrix} 
\right] 
$$

- 交换律：A+B=B+A
- 结合律：(A+B)+C=A+(B+C)
### 代码

In [1]:
import numpy as np
def plus(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """ 矩阵相加"""
    if x.shape == y.shape:
        return x + y

a = np.array([
    [1, 2],
    [2, 3]
])
b = np.copy(a)
c = plus(a, b)
c

array([[2, 4],
       [4, 6]])

### 矩阵乘法 Multiply   
- 矩阵A(m*p) X 矩阵B(p*n)  结论为C(m*n) 公式如下
$$
( AB )_{ij} = \sum^{p}_{k=1} A_{ik}b_{kj} = a_{i1}b_{1j} + a_{i2}b_{2j}+...+ a_{ip}b_{pj}
$$

- 例子

$$
\left[
 \begin{matrix}
   1 & 2 & 3 \\
   4 & 5 & 6 
  \end{matrix} 
\right] 
*
\left[
 \begin{matrix}
   1 & 4 \\
   2 & 5 \\  
   3 & 6   
   \end{matrix} 
\right] 
= 
\left[
 \begin{matrix}
   1*1+2*2+3*3 & 1*4+2*5+3*6 \\
   4*1+5*2+6*3 & 4*4+5*5+6*6 
   \end{matrix} 
\right] 
= \left[
 \begin{matrix}
   14 & 32 \\
   32 & 77   
   \end{matrix} 
\right] 
$$

### 代码

In [2]:
def multiply(x: np.ndarray, y) -> np.ndarray:
    """矩阵乘法"""
    return x.dot(y)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([
    [1, 4],
    [2, 5],
    [3, 6],
])
multiply(a,b)


array([[14, 32],
       [32, 77]])

### 哈达马乘积 Hadamard product
 哈达马乘积: 参与运算的矩阵必须是大小一样的(n,m都一样)
$$
\left[
 \begin{matrix}
   1 & 4 \\
   2 & 5 
   \end{matrix} 
\right]*
\left[
 \begin{matrix}
   1 & 4 \\
   2 & 5 
   \end{matrix} 
\right]
=\left[
 \begin{matrix}
   1*1 & 4*4 \\
   2*2 & 5*5 
   \end{matrix} 
\right]
=\left[
 \begin{matrix}
   1 & 16 \\
   4 & 25 
   \end{matrix} 
\right]
$$
### 代码

In [5]:
a = np.array([
    [1, 4],
    [2, 5]
])

a.dot(a)

array([[ 9, 24],
       [12, 33]])

### 转置 Transpose
设A为m×n阶矩阵（即m行n列），第i 行j 列的元素是a(i,j)

$$
\left[
 \begin{matrix}
   1 & 4 \\
   2 & 5 \\ 
   3 & 6 
   \end{matrix} 
\right]^T
= \
\left[
 \begin{matrix}
   1 & 2 & 3 \\
   4 & 5 & 6
   \end{matrix} 
\right]
$$
### 代码

In [3]:
def transpose(x: np.ndarray) -> np.ndarray:
    """矩阵转置"""
    return x.T

b = np.array([
    [1, 4],
    [2, 5],
    [3, 6],
])
transpose(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
def transpose2(x: np.ndarray) -> np.ndarray:
    """矩阵转置"""
    return x.transpose()
transpose2(b)

array([[1, 2, 3],
       [4, 5, 6]])

### 矩阵的行列式 Determinant
**行列式的计算必须是n*n的矩阵**
#### 2x2矩阵
$$
det(
\left[
 \begin{matrix}
   a & b  \\
   c & d 
   \end{matrix} 
\right]) = ad-bc
$$
### 代码

In [ ]:
def det(x: np.ndarray) -> np.ndarray:
    """行列式"""
    return np.linalg.det(x)
a = np.array([
    [1, 2],
    [3, 4],
])

det(a)

### 逆矩阵 Inverse


### 代码

In [ ]:
def inv(x: np.ndarray) -> np.ndarray:
    """矩阵求逆"""
    return np.linalg.inv(x)
a = np.array([
    [1, 2],
    [3, 4],
])
inv(a)

In [ ]:
def inv2(x: np.ndarray) -> np.ndarray:
    """矩阵求逆"""
    # np.matrix()废弃
    return np.matrix(x).I
a = np.array([
    [1, 2],
    [3, 4],
])
inv2(a)

### 矩阵的秩 Rank


### 代码

In [6]:
def rank(x: np.ndarray):
    return np.linalg.matrix_rank(x)

a = np.array([
    [1, 2],
    [3, 4],
])

rank(a)

2

### 迹 Trace

### 代码

In [9]:
def trace(x: np.ndarray):
    """矩阵trace"""
    return np.trace(x)
a = np.array([
    [1, 2],
    [3, 4],
])

trace(a)


5