# Numpy 的 nan 和 inf
## np.nan

In [1]:
import numpy as np

In [6]:
type(np.nan)

float

In [3]:
np.nan is None

False

In [4]:
np.isnan(np.nan)

True

In [5]:
np.nan == np.nan

False

In [8]:
np.nan +1

nan

In [9]:
np.nan *1

nan

### nan总结
- 判断`np.nan`不可用 `==np.nan`, 必须使用 `np.isnan()`
- `np.nan`不是`None`
- `np.nan`参与计算都是`np.nan`不会变

## np.inf

In [7]:
type(np.inf)

float

In [10]:
np.inf == np.inf

True

In [11]:
np.inf +1

inf

In [12]:
np.inf *1

inf

In [13]:
np.isinf(np.inf)

True

In [15]:
np.inf == None

False

### inf总结
- 判断是否为`np.inf`既可以使用`== np.inf` 也可以使用`np.isinf()`
- `np.inf`参与计算都是`np.inf`不会变


## 相关函数
- isinf
- isnan
- isneginf
- isposinf
- isfinite
- nan_to_num


In [18]:
a = np.array([
    np.inf,np.nan,3
])
np.nan_to_num(a)

array([1.79769313e+308, 0.00000000e+000, 3.00000000e+000])

In [19]:
np.isinf(a)

array([ True, False, False])

In [20]:
np.isnan(a)

array([False,  True, False])

In [21]:
np.isneginf(a)

array([False, False, False])

In [22]:
np.isfinite(a)

array([False, False,  True])

In [23]:
np.isposinf(a)

array([ True, False, False])