# NumPy 快速入门
## NumPy是什么
- [官方文档](https://NumPy.org/)中这么描述它
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
>    - a powerful N-dimensional array object (n维数组对象)
>    - sophisticated (broadcasting) functions (多种且复杂的函数)
>    - tools for integrating C/C++ and Fortran code (C/C++)
>    - useful linear algebra, Fourier transform, and random number capabilities (线性代数、傅里叶变换、随机数据功能)
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
> 
> NumPy is licensed under the BSD license, enabling reuse with few restrictions.
>

## 为什么用 NumPy
1. 运算速度快
1. 资源消耗少
1. 数据分析、机器学习、深度学习都需要它


## 安装
`pip install NumPy`

## NumPy核心基础
1. 在 NumPy 中数组为 ndarray 这是一个基础类型, NumPy 的函数都在对这个类型进行一次次的操作.
    1. 基本属性
        1. shape    : 维度
        1. dtype    : 数据类型
        1. ndim     : 轴数
        1. itemsize : 数组元素的字节大小
        1. axes     : 维度
        1. rank     : 维度数(轴数)
    1. 一个注意点
        1. **NumPy 的数组包含元素必须是同一类型**
        
### 什么是轴(维度)
> 通常我们将一个一维数组`[1,2,3]`称为一轴,二维数组称之为二轴,以此类推.

        
### 简单案例

In [7]:
import numpy as np
data = np.random.randn(1,10)

In [8]:
print("数据")
data

数据


array([[-1.25154005,  0.46726226,  1.62201538,  0.21359422, -0.64530671,
        -0.07477994,  0.28006409, -1.11943238,  1.20313767, -0.66464091]])

In [9]:
print("维度")
data.shape

维度


(1, 10)

In [11]:
data.dtype

dtype('float64')

In [12]:
data.ndim

2

In [12]:
data.itemsize


8

## 创建 ndarray
- `np.array(p_object)`
    - p_object 为list对象

In [ ]:
data_a = np.array([1,2,3])

In [3]:
np.array(1,2,3) # only 2 non-keyword arguments accepted

ValueError: only 2 non-keyword arguments accepted

- 不知道元素值的情况下创建
    - `np.zeros(shape=())`
        - 通过 shape 指定大小

In [4]:
data_b = np.zeros(shape=(2,2))
data_b


array([[0., 0.],
       [0., 0.]])

- 其他创建

In [12]:
np.empty(shape=(2,3,2))

array([[[1.14991112e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.73659984e-047]],

       [[2.14497085e+184, 3.11288615e+179],
        [8.38275718e+165, 3.34734179e-033],
        [2.22995107e+180, 2.44658277e-056]]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 输出 ndarray

In [5]:
print(data_b)

[[0. 0.]
 [0. 0.]]


- 超大数组输出会会略中间部分输出四角

In [10]:
print(np.arange(10000).reshape(1000,10))

[[   0    1    2 ...    7    8    9]
 [  10   11   12 ...   17   18   19]
 [  20   21   22 ...   27   28   29]
 ...
 [9970 9971 9972 ... 9977 9978 9979]
 [9980 9981 9982 ... 9987 9988 9989]
 [9990 9991 9992 ... 9997 9998 9999]]


- 强制输出所有
    `np.set_printoptions(threshold=sys.maxsize)`


## 数据类型
- 官方文档: 
    - https://numpy.org/doc/1.17/reference/arrays.scalars.html#arrays-scalars-built-in
    - https://numpy.org/doc/1.17/reference/arrays.dtypes.html?highlight=dtype
   
![numpy_data_type](https://numpy.org/doc/1.17/_images/dtype-hierarchy.png)
- 
### 默认数据类型
- `float_`
### python 内置数据类型
- int -> int_
- bool -> bool_
- float -> float_
- complex -> cfloat
- bytes -> bytes_
- str -> unicode_
- unicode -> unicode_
- buffer -> void


### 数据类型与字符码
#### 布尔
- bool_ -> ?
#### 整数
- byte -> b
- short h
- intc -> i
- int_ l
- longlong -> q
- intp -> p

#### 无符号整数

- ubyte -> B
- ushort -> H
- uintc -> I
- uint -> L
- ulonglong -> Q
- uintp -> P

#### 浮点数
- half -> e
- single -> f
- float_ -> d
- longfloat -> g


In [5]:
import numpy as np
dt = np.dtype(np.int_)
dt


dtype('int32')