# NumPy 快速入门
## NumPy是什么
- [官方文档](https://NumPy.org/)中这么描述它
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
>    - a powerful N-dimensional array object (n维数组对象)
>    - sophisticated (broadcasting) functions (多种且复杂的函数)
>    - tools for integrating C/C++ and Fortran code (C/C++)
>    - useful linear algebra, Fourier transform, and random number capabilities (线性代数、傅里叶变换、随机数据功能)
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
> 
> NumPy is licensed under the BSD license, enabling reuse with few restrictions.
>

## 为什么用 NumPy
1. 运算速度快
1. 资源消耗少
1. 数据分析、机器学习、深度学习都需要它


## 安装
`pip install NumPy`

## NumPy核心基础
1. 在 NumPy 中数组为 ndarray 这是一个基础类型, NumPy 的函数都在对这个类型进行一次次的操作.
    1. 基本属性
        1. shape    : 维度
        1. dtype    : 数据类型
        1. ndim     : 轴数
        1. itemsize : 数组元素的字节大小
        1. axes     : 维度
        1. rank     : 维度数(轴数)
    1. 一个注意点
        1. **NumPy 的数组包含元素必须是同一类型**
        
### 什么是轴(维度)
> 通常我们将一个一维数组`[1,2,3]`称为一轴,二维数组称之为二轴,以此类推.

        
### 简单案例

In [66]:
import numpy as np
data = np.random.randn(1,10)

In [ ]:
data

In [ ]:
data.shape

In [ ]:
data.dtype

In [ ]:
data.ndim

In [ ]:
data.itemsize


## 创建 ndarray
- `np.array(p_object)`
    - p_object 为list对象

In [ ]:
data_a = np.array([1,2,3])

In [ ]:
np.array(1,2,3) # only 2 non-keyword arguments accepted

- 不知道元素值的情况下创建
    - `np.zeros(shape=())`
        - 通过 shape 指定大小

In [ ]:
data_b = np.zeros(shape=(2,2))
data_b


- 其他创建

In [ ]:
np.empty(shape=(2,3,2))

In [ ]:
np.arange(10)

## 输出 ndarray

In [ ]:
print(data_b)

- 超大数组输出会会略中间部分输出四角

In [ ]:
print(np.arange(10000).reshape(1000,10))

- 强制输出所有
    `np.set_printoptions(threshold=sys.maxsize)`


## 数据类型
- 官方文档: 
    - https://numpy.org/doc/1.17/reference/arrays.scalars.html#arrays-scalars-built-in
    - https://numpy.org/doc/1.17/reference/arrays.dtypes.html?highlight=dtype
   
![numpy_data_type](https://numpy.org/doc/1.17/_images/dtype-hierarchy.png)
- 
### 默认数据类型
- `float_`
### python 内置数据类型
- int -> int_
- bool -> bool_
- float -> float_
- complex -> cfloat
- bytes -> bytes_
- str -> unicode_
- unicode -> unicode_
- buffer -> void


### 数据类型与字符码
#### 布尔
- bool_ -> ?
#### 整数
- byte -> b
- short h
- intc -> i
- int_ l
- longlong -> q
- intp -> p

#### 无符号整数

- ubyte -> B
- ushort -> H
- uintc -> I
- uint -> L
- ulonglong -> Q
- uintp -> P

#### 浮点数
- half -> e
- single -> f
- float_ -> d
- longfloat -> g


In [ ]:
import numpy as np
dt = np.dtype(np.int_)
dt

## 基础操作
- 以一维数据作为演示用例[1,2,3]
### 加法

In [ ]:
a = np.array([1,2,3])
a +1

### 减法

In [ ]:
a - 1

### 乘法

In [ ]:
a *2

### 除法

In [ ]:
a /2

### 小心使用 +=、-=、*=、/=
> 这些符号会修改原始值,用例如下

In [ ]:
b = np.array([1,2,3])
b+=1
b

### 向上转型
> 当不同数据类型进行运算时,运算结果会采取更加精确的数据类型

In [ ]:
c = np.array([1,2,3],dtype=np.int_)
d = np.array([1.1,2.2,3.3],dtype=np.float_)
e = np.array(c+d) # 可以直接 c+d 为了方便用.调用方法在此处进行了np.array()构造一个 ndarray
e.dtype

### 数学函数
- 常用数学函数sum(),max(),min(),sin(),cos(),tan(),sqrt(),exp()反三角函数等不在此例举.

#### sum

In [ ]:
a = np.array([1,2,3])
a.sum()

#### max

In [ ]:
a.max()

#### min

In [ ]:
a.min()

#### sin

In [ ]:
np.sin(a)

#### cos

In [ ]:
np.cos(a)

#### tan

In [ ]:
np.tan(a)

#### sqrt

In [ ]:
np.sqrt(a)

#### exp

In [ ]:
np.exp(a)

## 索引、切片、迭代

### 一维数组
> 一维数组和`list`操作一致
>

In [ ]:
a = np.arange(10)
a

In [ ]:
# 索引
a[1]

In [ ]:
# 切片
a[1:4]

In [ ]:
# 迭代
for i in a:
    print(i)

### 多维数组

In [80]:
# 随机数组后续使用
def func(x,y):
    return x+y
a = np.fromfunction(function=func , shape=(3,5))
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

- ndarray[n] 选取第n维度的数据
- ndarray[n,m] 选取第n维度的第m个数据

In [85]:
# 索引
a[1]

array([1., 2., 3., 4., 5.])

In [88]:
a[1,3]

4.0

In [99]:
# 切片
# 选择那几行,第几列
a[1:3,2]

array([3., 4.])

In [111]:
def func2(x,y,z):
    return 10*x+10*y + z

b = np.fromfunction(function = func2,shape=(3,2,3))
b

array([[[ 0.,  1.,  2.],
        [10., 11., 12.]],

       [[10., 11., 12.],
        [20., 21., 22.]],

       [[20., 21., 22.],
        [30., 31., 32.]]])

In [121]:
# 维度越高[]切片表达式越复杂
b[0:2,1,1]


array([11., 21.])

In [124]:
for i in b:
    print(i)
    

[[ 0.  1.  2.]
 [10. 11. 12.]]
[[10. 11. 12.]
 [20. 21. 22.]]
[[20. 21. 22.]
 [30. 31. 32.]]


> 索引、切片、迭代笔者没有办法给出一个很明确的使用指南,也是摸索着一点点使用,一般的记忆方式为`:`获取维度范围,`,`获取具体位置数据
>
>
