# Numpy 读取写出
## 写出
- `np.save` 默认拓展名 `.npy`

In [11]:
import numpy as np

'E:\\pycharm_project\\test_data\\np-out.npy'

In [19]:
d = np.arange(9)
np.save("out.npy",d)

- `np.savez` 拓展名为 `.npz`

In [25]:
# 写出的为一个dict{a1:d}
np.savez("out.npz",a1=d)

- `np.savetxt` 

In [18]:
np.savetxt("out",d)


## 读取
- `np.load`

In [20]:
np.load("out.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# 读取时选择key
np.load("out.npz")["a1"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

- `np.loadtxt`

In [27]:
np.loadtxt("out")

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])