# Numpy 特征值替换
## 将某一个值替换
通过 `ndarry[ndarry == 特征值 ] = 目标值` 实现,代码如下

In [1]:
import numpy as np
d = np.zeros((3,3,3))
d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
d[d==0]=1
d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

- 类型转换

In [4]:
d = d.astype(dtype=np.int_)
d

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

## 复杂的条件
- 对第几行进行替换

In [17]:
d = np.zeros((2,2),dtype=np.int_)
d

array([[0, 0],
       [0, 0]])

In [19]:
d[:1]=2
d

array([[2, 2],
       [0, 0]])

- 对第几列进行替换

In [20]:
d[:,1]=5
d

array([[2, 5],
       [0, 5]])

- 增加条件

In [22]:
d[:,1][d[:,1]>=5] = 10
d


array([[ 2, 10],
       [ 0, 10]])