# 集合操作
- `np.in1d`测试是否存在

In [2]:
import numpy as np


test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
mask = np.in1d(test, states)
# 返回test和state的关系
mask

array([ True, False,  True, False,  True])

In [3]:
test[mask]

array([0, 2, 0])

In [4]:
# 取反
mask = np.in1d(test, states, invert=True)
mask

array([False,  True, False,  True, False])

In [5]:
test[mask]

array([1, 5])

- `np.intersect1d`交集

In [6]:
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
np.intersect1d(test,states)

array([0, 2])

- `np.union1d`并集

In [7]:
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
np.union1d(test,states)

array([0, 1, 2, 5])

- `np.setxor1d`差集

In [11]:
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
np.setxor1d(test,states)

# np.setdiff1d(test,states)

array([1, 5])