# 统计
- `np.median`中位数

In [3]:
import numpy as np

a = np.arange(10)
np.median(a)

4.5

- `np.average`  加权平均值

In [5]:
np.average(a)

4.5

- `np.mean` 算术平均值

In [6]:
np.mean(a)

4.5

- `np.std`标准差

In [7]:
np.std(a)

2.8722813232690143

- `np.var`方差

In [8]:
np.var(a)

8.25

- 轴向中位数

In [11]:
a = np.array([
    [1,2],
    [2,3],
])

np.nanmedian(a,axis=0)

array([1.5, 2.5])

- `np.amin`最大值(计算nan)
- `np.amax`最小值(计算nan)
- `np.nanmin`最大值(不计算nan)
- `np.nanmax`最小值(不计算nan)

In [13]:
a = np.arange(4).reshape((2,2))
np.amin(a,axis=0)

array([0, 1])

In [14]:
np.amin(a)

0

In [18]:
np.amax(a)

3

In [17]:
np.amax(a,axis=1)

array([1, 3])